name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: [10.0.x, 10.x, 12.0.x, 12.x, 14.0.x, 14.x, 16.x]
        platform:
        - os: ubuntu-latest
          shell: bash
        - os: macos-latest
          shell: bash
        - os: windows-latest
          shell: bash
        - os: windows-latest
          shell: powershell
      fail-fast: false

    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1.1.0

      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use latest npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Run Tests (no linting)
        if: matrix.platform.os != 'ubuntu-latest' || matrix.node-version != '16.x'
        run: npm test --ignore-scripts -- -c -t0
        env:
          RIMRAF_TEST_START_CHAR: a
          RIMRAF_TEST_END_CHAR: j
          RIMRAF_TEST_DEPTH: 5

      - name: Run Tests
        if: matrix.platform.os == 'ubuntu-latest' && matrix.node-version == '16.x'
        run: npm test -- -t0 -c
        env:
          RIMRAF_TEST_START_CHAR: a
          RIMRAF_TEST_END_CHAR: j
          RIMRAF_TEST_DEPTH: 5
